# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_requestassistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsPaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_one', models.CharField(blank=True, max_length=200, null=True)),
                ('ket_two', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventModel')),
            ],
        ),
    ]
