# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_methodspaymentevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodspaymentevent',
            name='event',
        ),
        migrations.DeleteModel(
            name='MethodsPaymentEvent',
        ),
    ]
