# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='config_platform/')),
                ('color_one', models.CharField(max_length=8)),
                ('color_two', models.CharField(max_length=8)),
                ('color_three', models.CharField(max_length=8)),
                ('video_home', models.FileField(upload_to='config_platform/')),
                ('banner_one', models.ImageField(upload_to='config_platform/')),
                ('banner_two', models.ImageField(upload_to='config_platform/')),
            ],
        ),
    ]
