# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configplatform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configplatform',
            name='video_home',
        ),
        migrations.AlterField(
            model_name='configplatform',
            name='color_one',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='configplatform',
            name='color_three',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='configplatform',
            name='color_two',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
