# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configplatform', '0002_auto_20170511_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='configplatform',
            name='video_home',
            field=models.FileField(blank=True, null=True, upload_to='config_platform/'),
        ),
    ]
