# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configplatform', '0003_configplatform_video_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configplatform',
            name='video_home',
        ),
        migrations.AddField(
            model_name='configplatform',
            name='video_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
