# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(upload_to='image_profile/')),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('address_two', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('address_billing', models.CharField(blank=True, max_length=150, null=True)),
                ('address_two_billing', models.CharField(blank=True, max_length=150, null=True)),
                ('city_billing', models.CharField(blank=True, max_length=30, null=True)),
                ('country_billing', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code_billing', models.IntegerField(blank=True, null=True)),
                ('address_shipping', models.CharField(blank=True, max_length=150, null=True)),
                ('address_two_shipping', models.CharField(blank=True, max_length=150, null=True)),
                ('city_shipping', models.CharField(blank=True, max_length=30, null=True)),
                ('country_shipping', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code_shipping', models.IntegerField(blank=True, null=True)),
                ('address_work', models.CharField(blank=True, max_length=150, null=True)),
                ('address_two_work', models.CharField(blank=True, max_length=150, null=True)),
                ('city_work', models.CharField(blank=True, max_length=30, null=True)),
                ('country_work', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code_work', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('preferences', models.ManyToManyField(to='events.TypeEventModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
