# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/'),
        ),
    ]
