# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_sheller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 25, 17, 8, 55, 806044)),
        ),
    ]
