# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 25, 19, 40, 56, 247690)),
        ),
    ]
