# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20170525_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_methods/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 31, 2, 55, 9, 472464)),
        ),
    ]
