# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170531_0256'),
        ('tickets', '0005_auto_20170531_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsPaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_one', models.CharField(blank=True, max_length=200, null=True)),
                ('ket_two', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventModel')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.PaymentMethod')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 31, 2, 56, 22, 650242)),
        ),
    ]
