# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20170601_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 1, 21, 30, 56, 267848)),
        ),
    ]
